export const NEWSCATEGORY = {
    All: 'all',
    AUTOMOBILE: 'automobile',
    BUSINESS: 'business',
    ENTERTAINMENT: 'entertainment',
    HATKE: 'hatke',
    MISCELLANEOUS: 'miscellaneous',
    NATIONAL: 'national',
    POLITICS: 'politics',
    SCIENCE: 'science',
    SPORTS: 'sports',
    STARTUP: 'startup',
    TECHNOLOGY: 'technology',
    WORLD: 'world',
}